function output = importquestionnaire(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PARTICIPANTPROFILINGQUESTIONNAIRE = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  PARTICIPANTPROFILINGQUESTIONNAIRE = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Participantprofilingquestionnaire = importfile("/Users/turux/OneDrive - Loughborough University/eBike/WattBike Test/Questionnarie/Participant profiling questionnaire.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Apr-2019 17:28:15

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 24);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Timestamp", "Name", "Email", "Age", "Gender", "WeightKg", "Heightcm", "Doyouexercise", "Doyoucycle", "Whatbikedoyouusuallyuse", "Wheredoyouusuallycycle", "Whatterrainyougenerallyrideon", "Hourscycledperweek", "DistancecycledperweekKm", "Howmanytimesdoyoucycleperweek", "DistancecycledpertripKm", "Intensityofcycling", "Typeofcyclist", "Doyoudootherkindofexercise", "Otherhoursofexercise", "Whattypeofexercise", "Intensityofexercise", "Typeoffitness", "Whatisyourperceivedleveloffitness"];
opts.VariableTypes = ["string", "string", "string", "double", "categorical", "double", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "double", "double", "categorical", "categorical", "categorical", "double", "categorical", "categorical", "categorical", "double"];
opts = setvaropts(opts, [1, 2, 3], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 5, 8, 9, 10, 11, 12, 17, 18, 19, 21, 22, 23], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
output = readtable(filename, opts);

end