function test = wbimport(filepath)
%IMPORTFILE Import data from a text file
%  TEST = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  TEST = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  test = importfile("/Users/turux/OneDrive - Loughborough University/eBike/WattBike Test/2018 Tests/03/PART03.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Apr-2019 12:00:23

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 1
    [filename, filepath] = uigetfile('*.txt','Select the WattBike File');
    filename = fullfile(filepath, filename);
else
    filename = dir(fullfile(filepath,'*txt'));
    filename = fullfile(filepath, filename.name);
end

dataLines = [2, Inf];

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 44);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Index", "Elapsedtimehmmsshh", "Elapsedtimetotalhmmsshh", "TurnsnumberNr", "Cadencerpm", "Cadencepeakrpm", "Cadenceaveragerpm", "Circpedalvelocityms", "Speedkmh", "Avrspeedkmh", "Distancem", "Distancetotalm", "Heartratebpm", "Heartratepeakbpm", "Heartrateaveragebpm", "ForceN", "ForcepeaktotalN", "ForcepeakN", "AvrforceN", "TorqueNm", "AvrtorqueNm", "Pace1000msec", "Avrpace1000msec", "PowerW", "PowerpeakrevW", "AvrpowerW", "PowerKgWKg", "AvrpowerKgWKg", "Caloriescal", "CaloriestotalKcal", "WorkJ", "WorktotalKJ", "Leftlegpercent", "Totalleftlegpercent", "Rightlegpercent", "Totalrightlegpercent", "Lefttimetoforcepeakmmss00", "Totallefttimetoforcepeakmmss00", "Righttimetoforcepeakmmss00", "Totalrighttimetoforcepeakmmss00", "Leftangletoforcepeak", "Totalleftangletoforcepeak", "Rightangletoforcepeak", "Totalrightangletoforcepeak"];
opts.VariableTypes = ["double", "datetime", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "categorical", "categorical", "categorical", "double", "double", "double", "double"];
opts = setvaropts(opts, 2, "InputFormat", "H:mm:ss.SS");
opts = setvaropts(opts, 3, "InputFormat", "H:mm:ss.SS");
opts = setvaropts(opts, [22, 23], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [22, 23, 37, 38, 39, 40], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data

lastwarn('') % Clear last warning message
test = readtable(filename, opts);
[warnMsg, warnId] = lastwarn;
if ~isempty(warnMsg)
    opts = setvaropts(opts, 2, "InputFormat", "mm:ss.S");
    opts = setvaropts(opts, 3, "InputFormat", "mm:ss.S");
    test = readtable(filename, opts);
end


end