function wbdata = wbimport()
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/turux/Loughborough University/(s) Dan Loftus - Cycling performance monitoring and modelling project/2017 Test Results/20171207/Pete 60min/revs.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/12/08 13:42:14

%% Initialize variables.
%filename = '/Users/turux/Loughborough University/(s) Dan Loftus - Cycling performance monitoring and modelling project/2017 Test Results/20171207/Pete 60min/revs.txt';
[filename, filepath] = uigetfile('*.txt','Select the WattBike File');
filename = fullfile(filepath, filename);
delimiter = '\t';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: categorical (%C)
%   column3: text (%s)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: categorical (%C)
%   column23: categorical (%C)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: categorical (%C)
%	column38: categorical (%C)
%   column39: categorical (%C)
%	column40: categorical (%C)
%   column41: double (%f)
%	column42: double (%f)
%   column43: double (%f)
%	column44: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%C%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%C%C%f%f%f%f%f%f%f%f%f%f%f%f%f%C%C%C%C%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
wbdata = table(dataArray{1:end-1}, 'VariableNames', {'Index','Elapsedtimehmmsshh','Elapsedtimetotalhmmsshh','TurnsnumberNr','Cadencerpm','Cadencepeakrpm','Cadenceaveragerpm','Circpedalvelocityms','Speedkmh','Avrspeedkmh','Distancem','Distancetotalm','Heartratebpm','Heartratepeakbpm','Heartrateaveragebpm','ForceN','ForcepeaktotalN','ForcepeakN','AvrforceN','TorqueNm','AvrtorqueNm','Pace1000msec','Avrpace1000msec','PowerW','PowerpeakrevW','AvrpowerW','PowerKgWKg','AvrpowerKgWKg','Caloriescal','CaloriestotalKcal','WorkJ','WorktotalKJ','Leftlegpercent','Totalleftlegpercent','Rightlegpercent','Totalrightlegpercent','Lefttimetoforcepeakmmss00','Totallefttimetoforcepeakmmss00','Righttimetoforcepeakmmss00','Totalrighttimetoforcepeakmmss00','Leftangletoforcepeak','Totalleftangletoforcepeak','Rightangletoforcepeak','Totalrightangletoforcepeak'});

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;